In [1]:
from keras.models import load_model
import os
import numpy as np
from keras.preprocessing import image

# 成功率 55%

model = load_model('All.h5')

def pred(img):
    
    print(img)
    img = image.load_img(img, target_size=(150,150))
    
    img = img.rotate(-90)
    img.show()

    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    #x = preprocess_input(x)

    result = model.predict(x)
    print(result)


    Max = 0.0
    for j in result:
        for i, c in enumerate(j):
            if c > Max:
                print(c, Max)
                Max = i
                a = i

    print(a)

    if a == 0:
        print('Timberland')

    elif a == 1:
        print('addidas')

    elif a == 2:
        print('pierre cardin')

    elif a == 3:
        print('幸福台灣')

    elif a == 4:
        print('春水堂')

    else:
        pass
        
    import time
    time.sleep(5)

Using TensorFlow backend.


test/IMG_2950.JPG
[[0. 0. 1. 0. 0.]]
1.0 0.0
2
pierre cardin
test/IMG_2944.JPG
[[0. 0. 0. 1. 0.]]
1.0 0.0
3
幸福台灣
test/IMG_2945.JPG
[[0. 1. 0. 0. 0.]]
1.0 0.0
1
addidas
test/IMG_2951.JPG
[[1. 0. 0. 0. 0.]]
1.0 0.0
0
Timberland
test/IMG_2947.JPG
[[1. 0. 0. 0. 0.]]
1.0 0.0
0
Timberland
test/IMG_2953.JPG
[[0. 1. 0. 0. 0.]]
1.0 0.0
1
addidas
test/IMG_2952.JPG
[[0. 0. 0. 1. 0.]]
1.0 0.0
3
幸福台灣
test/IMG_2946.JPG
[[0. 0. 0. 0. 1.]]
1.0 0.0
4
春水堂
test/IMG_2942.JPG
[[0. 1. 0. 0. 0.]]
1.0 0.0
1
addidas
test/.DS_Store


OSError: cannot identify image file 'test/.DS_Store'

In [ ]:
#img = 'dataset/Timberland/IMG_1909 075.jpg'
img = 'dataset/validation/幸福台灣/IMG_1904 110.jpg'

print(img)
    
img = image.load_img(img, target_size=(150,150))
#img.show()

x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
    
result = model.predict(x)
print(result)